// Avatars are generated by DiceBear (https://dicebear.com) and served as SVG
// images over HTTP. An avatar value is stored as "style:seed", which fully
// describes how to render it anywhere in the app.

const DICEBEAR = "https://api.dicebear.com/9.x";

export interface AvatarStyle {
  id: string;
  label: string;
}

// A handful of "little character" styles to pick from.
export const AVATAR_STYLES: AvatarStyle[] = [
  { id: "adventurer", label: "Aventuriers" },
  { id: "bottts", label: "Robots" },
  { id: "fun-emoji", label: "Emojis" },
  { id: "open-peeps", label: "Peeps" },
  { id: "pixel-art", label: "Pixel" },
  { id: "lorelei", label: "Portraits" },
  { id: "micah", label: "Minimal" },
  { id: "thumbs", label: "Pouces" },
];

// Distinct seeds -> distinct characters within a style.
export const AVATAR_SEEDS = [
  "Milo", "Luna", "Felix", "Zoe", "Leo", "Nina",
  "Max", "Cleo", "Otis", "Ivy", "Hugo", "Maya",
  "Remy", "Lola", "Theo", "Suki", "Bram", "Juno",
  "Axel", "Wren", "Gus", "Pixie", "Dash", "Coco",
  "Rex", "Kira", "Niko", "Tess", "Bo", "Yuki",
];

const STYLE_IDS = new Set(AVATAR_STYLES.map((s) => s.id));

export const DEFAULT_AVATAR = "adventurer:Milo";

export function makeAvatar(style: string, seed: string): string {
  return `${style}:${seed}`;
}

export function avatarUrl(value: string): string {
  const idx = (value || "").indexOf(":");
  let style = "adventurer";
  let seed = "Milo";
  if (idx >= 0) {
    style = value.slice(0, idx);
    seed = value.slice(idx + 1);
  } else if (value) {
    seed = value; // legacy value without a style prefix
  }
  if (!STYLE_IDS.has(style)) style = "adventurer";
  return `${DICEBEAR}/${encodeURIComponent(style)}/svg?seed=${encodeURIComponent(
    seed
  )}`;
}
